apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default

  sources:
    # 1) Helm chart source
    - repoURL: https://helm.cilium.io
      chart: cilium
      targetRevision: 1.16.5
      helm:
        releaseName: cilium
        valueFiles:
          - $values/apps/cilium/values.yaml

    # 2) Values repo source
    - repoURL: https://github.com/DocFitz/testAKS.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: false #prevent crds from being removed during upgrades
      selfHeal: true
    syncOptions:
    - CreateNamespace=true