cluster:
  name: aks-cluster
  id: 1

aksbyocni:
  enabled: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 192.168.0.0/16

# cilium will pick its own default node size. here we can state it
# in this case we'd have 256 pod ips
# ipam:
#  operator:
#    clusterPoolIPv4MaskSize: 24


routingMode: tunnel
ipv4NativeRoutingCIDR: 10.0.0.0/8

kubeProxyReplacement: false

bpf:
  masquerade: true

# enable if kube-proxy masquerade logs indicated in crashing
# enableNodePort: true


hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

