cluster:
  name: aks-cluster
  id: 1

aksbyocni:
  enabled: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 192.168.0.0/16

routingMode: native
ipv4NativeRoutingCIDR: 10.0.0.0/8

kubeProxyReplacement: false

bpf:
  masquerade: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

