apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-echo
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-echo
    owner: platform
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-echo
  template:
    metadata:
      labels:
        app: demo-echo
        owner: platform
    spec:
      containers:
        - name: demo-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
