apiVersion: v1
kind: Service
metadata:
  name: demo-echo
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-echo
    owner: platform
spec:
  selector:
    app: demo-echo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
